### PR TITLE
ARM Support

### PR DESCRIPTION
**Pull request by zaoqi**

### CODE REVIEW

**Comment by zaoqi** [comment]
@TheAssassin 
linuxdeploy and linuxdeploy-plugin-appimage circular dependencies?

**Comment by TheAssassin** [comment]
This is a huge and unclear single-commit PR. I tend to close it, since this kind of "flat commit" is super annoying to debug. I cannot track the history of your changes.

The way you send PRs makes it *really difficult* for the maintainers to check and accept them.

Even worse, your PR is failing on Travis CI for some reason...

**Comment by zaoqi** [comment]
These 2 PR needs to be merged to not fail on Travis CI

**Comment by TheAssassin** [comment]
Closing as outdated.

**Pull request closed without merging**
