### PR TITLE
Attempt to allow Building of armhf and aarch64

### PR DESCRIPTION
**Pull request by sithlord48**
Add `armhf` and `aarch64` to the list of build-able architectures
Todo : Replace container build  with a proper docker setup

This will be required for https://github.com/linuxdeploy/linuxdeploy/pull/189 
Works until it fails to pull linuxdeploy-arch from github for [armhf](https://github.com/sithlord48/linuxdeploy-plugin-appimage/actions/runs/4398352244/jobs/7702142892#step:3:3098) and [aarch64](https://github.com/sithlord48/linuxdeploy-plugin-appimage/actions/runs/4398352244/jobs/7702142846#step:3:3119)

### CODE REVIEW

**Comment by christianparpart** [comment]
Hey guys. Any updates on this? I'm not trying to push, but I was almost about to create a new ticket to request adding support for ARM64 (aarch64) binaries, ready for download in the release page, as I am working on Linux ARM64 on a daily basis. I keep getting thrown back from time to time due to lag of support of some little software projects that I'd like to give some more attention to however :)

**Comment by TheAssassin** [comment]
I'm not a fan of third-party actions, however that could be solved. I wonder, though, if this really not-so-complex tool couldn't just be cross-compiled on Ubuntu with clang or `g++-aarch64-linux-gnu`?

**Comment by TheAssassin** [comment]
Anyway, the main issue I have with this PR is the use of that third-party action. In my opinion, CI should always be written in a way so the majority can be run locally (and on virtually any CI system). The actions code should be limited to the minimum required to run all required configurations.

**Comment by johnnynunez** [comment]
https://github.blog/news-insights/product-news/arm64-on-github-actions-powering-faster-more-efficient-build-systems/ solved @TheAssassin

**Pull request closed without merging**
